create table "public"."parking-tickets" (
    "id" bigint generated by default as identity not null,
    "parkingLotId" uuid not null,
    "userId" uuid,
    "created_at" timestamp with time zone not null default now(),
    "status" character varying default 'pending'::character varying,
    "plate" character varying
);


CREATE UNIQUE INDEX "parking-tickets_pkey" ON public."parking-tickets" USING btree (id);

alter table "public"."parking-tickets" add constraint "parking-tickets_pkey" PRIMARY KEY using index "parking-tickets_pkey";

alter table "public"."parking-tickets" add constraint "parking-tickets_parkingLotId_fkey" FOREIGN KEY ("parkingLotId") REFERENCES "parking-lots"(id) not valid;

alter table "public"."parking-tickets" validate constraint "parking-tickets_parkingLotId_fkey";

alter table "public"."parking-tickets" add constraint "parking-tickets_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."parking-tickets" validate constraint "parking-tickets_userId_fkey";

grant delete on table "public"."parking-tickets" to "anon";

grant insert on table "public"."parking-tickets" to "anon";

grant references on table "public"."parking-tickets" to "anon";

grant select on table "public"."parking-tickets" to "anon";

grant trigger on table "public"."parking-tickets" to "anon";

grant truncate on table "public"."parking-tickets" to "anon";

grant update on table "public"."parking-tickets" to "anon";

grant delete on table "public"."parking-tickets" to "authenticated";

grant insert on table "public"."parking-tickets" to "authenticated";

grant references on table "public"."parking-tickets" to "authenticated";

grant select on table "public"."parking-tickets" to "authenticated";

grant trigger on table "public"."parking-tickets" to "authenticated";

grant truncate on table "public"."parking-tickets" to "authenticated";

grant update on table "public"."parking-tickets" to "authenticated";

grant delete on table "public"."parking-tickets" to "service_role";

grant insert on table "public"."parking-tickets" to "service_role";

grant references on table "public"."parking-tickets" to "service_role";

grant select on table "public"."parking-tickets" to "service_role";

grant trigger on table "public"."parking-tickets" to "service_role";

grant truncate on table "public"."parking-tickets" to "service_role";

grant update on table "public"."parking-tickets" to "service_role";


