name: deploy-to-dev
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: qvxfqvelwftasitvnega
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase migration up
      - run: supabase db push
